// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendorRiskAPI.Infrastructure.Persistence;

#nullable disable

namespace VendorRiskAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendorRiskAPI.Domain.Entities.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssessedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("FinalRiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("FinancialRiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("OperationalRiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SecurityComplianceRiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessedAt");

                    b.HasIndex("FinalRiskScore");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("VendorId");

                    b.ToTable("RiskAssessments", (string)null);
                });

            modelBuilder.Entity("VendorRiskAPI.Domain.Entities.VendorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinancialHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MajorIncidents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecurityCerts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("SlaUptime")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FinancialHealth");

                    b.HasIndex("Name");

                    b.HasIndex("SlaUptime");

                    b.ToTable("VendorProfiles", (string)null);
                });

            modelBuilder.Entity("VendorRiskAPI.Domain.Entities.RiskAssessment", b =>
                {
                    b.HasOne("VendorRiskAPI.Domain.Entities.VendorProfile", "Vendor")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VendorRiskAPI.Domain.Entities.VendorProfile", b =>
                {
                    b.OwnsOne("VendorRiskAPI.Domain.ValueObjects.DocumentValidation", "Documents", b1 =>
                        {
                            b1.Property<int>("VendorProfileId")
                                .HasColumnType("integer");

                            b1.Property<bool>("ContractValid")
                                .HasColumnType("boolean");

                            b1.Property<bool>("PentestReportValid")
                                .HasColumnType("boolean");

                            b1.Property<bool>("PrivacyPolicyValid")
                                .HasColumnType("boolean");

                            b1.HasKey("VendorProfileId");

                            b1.ToTable("VendorProfiles");

                            b1.WithOwner()
                                .HasForeignKey("VendorProfileId");
                        });

                    b.Navigation("Documents")
                        .IsRequired();
                });

            modelBuilder.Entity("VendorRiskAPI.Domain.Entities.VendorProfile", b =>
                {
                    b.Navigation("RiskAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
